#!/usr/bin/env python3

import sys
import os

def generateResourceHeader(outputFile, *resourceFiles):    
    resources = {}
    
    for resourceFile in resourceFiles:
        if not os.path.exists(resourceFile):
            print(f"Warning: {resourceFile} not found", file=sys.stderr)
            continue
        
        resourceName = os.path.basename(resourceFile)
        
        with open(resourceFile, 'r', encoding='utf-8') as f:
            content = f.read()
        
        resources[resourceName] = content
    
    headerGuard = "JORGESCRIPT_RESOURCES_HPP"
    
    with open(outputFile, 'w', encoding='utf-8') as f:
        f.write(f"""// THIS FILE IS AUTOMATICALLY GENERATED!! DO NOT EDIT!!
#pragma once
#include <unordered_map>
#include <string>

namespace Resources {{

""")
        
        for resourceName, content in resources.items():
            varName = resourceName.replace('.', '_').replace('-', '_').upper()
            f.write(f'    constexpr std::string_view {varName} = R"___JORG___({content})___JORG___";\n\n')
        
        f.write("""    inline const std::unordered_map<std::string, std::string_view>& getResources() {
        static const std::unordered_map<std::string, std::string_view> resources = {
""")
        
        for resourceName in sorted(resources.keys()):
            varName = resourceName.replace('.', '_').replace('-', '_').upper()
            f.write(f'            {{"{resourceName}", {varName}}},\n')
        
        f.write("""        };
        return resources;
    }

    inline bool hasResource(const std::string& name) {
        return getResources().count(name) > 0;
    }

    inline std::string_view getResource(const std::string& name) {
        auto& resources = getResources();
        auto it = resources.find(name);
        if (it != resources.end()) {
            return it->second;
        }
        return "";
    }

} // namespace Resources
""")

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: python generate_resources.py <output_header> <resource1> [resource2] ...", file=sys.stderr)
        sys.exit(1)
    
    outputFile = sys.argv[1]
    resourceFiles = sys.argv[2:]
    
    generateResourceHeader(outputFile, *resourceFiles)
    print(f"Generated {outputFile}")
